CREATE DATABASE MESSAGESTATUS;

CREATE TABLE MessageStatuss(
MessageReactions VARCHAR(150) NOT NULL,
UnsendMessage VARCHAR(150) NOT NULL,
SearchMessagesOrMembers VARCHAR(150) NOT NULL,
GroupChat VARCHAR(150) NOT NULL
)

SELECT * FROM MessageStatuss;